### ISSUE TITLE
Missing treatment

### ISSUE THREAD

**Issue by millerjeremya** [plazi/GoldenGATE-Imagine#50] opened 2023-10-15 16:29 UTC
@myrmoteras @flsimon
Looking into this treatment - appears to come up as having no text. 
https://treatment.plazi.org/GgServer/html/FE5887E47B3CA86E9DC0FF3BB102FBF2
I would appreciate some help with troubleshooting.

**Comment by gsautter** [comment] 2023-10-16 02:11
As https://treatment.plazi.org/GgServer/xml/FE5887E47B3CA86E9DC0FF3BB102FBF2 shows, the whole treatment text is marked as a `caption`, and without the `inLine` attribute, which effectively has its text hidden in the HTML ... going to take care of it.

**Comment by gsautter** [comment] 2023-10-16 02:40
Fixed ... see https://treatment.plazi.org/GgServer/xml/FE5887E47B3CA86E9DC0FF3BB102FBF2/4 for the previous version of the XML, and https://treatment.plazi.org/GgServer/xml/FE5887E47B3CA86E9DC0FF3BB102FBF2 for the current version with the `inLine` flag on the caption.

**Comment by millerjeremya** [comment] 2023-10-16 07:55
Thanks for the help.
A couple things I notice now, first there appears to be a materialCitation that shows up in TB as though it's a figure citation, plus some other unexpected figure citation links. 
GGI
![image](https://github.com/plazi/GoldenGATE-Imagine/assets/4322250/48562dbb-4d37-46dc-9384-81858ff5f3a4)
TB
![image](https://github.com/plazi/GoldenGATE-Imagine/assets/4322250/d1ef0f1f-f57f-4031-bc39-9453218b8bfe)

Also, the rendering of the figure is missing some elements, specifically the line drawing and annotations.
GGI
![image](https://github.com/plazi/GoldenGATE-Imagine/assets/4322250/6d8de37f-f1e6-4d2f-bbf5-9e17ccfbd959)
TB
![image](https://github.com/plazi/GoldenGATE-Imagine/assets/4322250/78fd0f48-4850-4fcb-a3c5-15b7033b6a22)

**Comment by gsautter** [comment] 2023-10-16 08:03
Well, the whole `treatment` is (and was) marked as a `caption` (which is why the text didn't show at all), and all I did was mark the `caption` with the `inLine` attribute, which signals the TB website to display the text despite its being inside a `caption` ... the "View Figure" showing after every paragraph is basically the result of the rare (and unintended) case that an in-line `caption` spans more than a sentence or two ... for the line drawing to show as well, we'll have to mark the whole figure as one, or connect the figures via "Bottom Extend" or "Right Extend" ... I tend to think the former will do ... the original question was only about the treatment text now showing, though ...

**Comment by gsautter** [comment] 2023-10-16 08:09
The reason the `materialsCitation` only shows up now is because now it's inside a single `subSubSection` and `paragraph`, which it wasn't before, as it was marked across a `paragraph` boundary.

**Comment by gsautter** [comment] 2023-10-16 08:17
> Well, the whole `treatment` is (and was) marked as a `caption` (which is why the text didn't show at all), and all I did was mark the `caption` with the `inLine` attribute, which signals the TB website to display the text despite its being inside a `caption` ... the "View Figure" showing after every paragraph is basically the result of the rare (and unintended) case that an in-line `caption` spans more than a sentence or two ... for the line drawing to show as well, we'll have to mark the whole figure as one, or connect the figures via "Bottom Extend" or "Right Extend" ... I tend to think the former will do ... the original question was only about the treatment text now showing, though ...

Figured out why that line drawing doesn't come up with the image ... it's conflated with the gray bar and black line across the page top into a single `graphics` object, and therefor doesn't work as intended ... unfortunately, that black line does not repeat on all the pages, either, so GGI has no way of telling it is for of page decoration (akin to the lighter and thinner line further above it) ... tough one, will have to think about it ... maybe we need an option for cutting graphics supplements apart ...

**Comment by gsautter** [comment] 2023-10-23 01:58
Export of the vector portions of the figure is fixed with the update I just deployed. Cannot update the figure on Zenodo right now, though, as there seems to be a permission issue with uploading new files ... in contact with Zenodo developers in that regard.

**Closed as completed by gsautter** 2023-10-23 01:58 UTC
